name: My Feishu Talk Bot Push
on:
  workflow_dispatch:
    schedules:
      cron: '*/3 * * * *'

jobs:
  run-python-script:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: run python script
        run: |
          python PushWeiboHotSearchRegularly.py
          python TodayInHistory.py
          python WeatherForecast.py
        env:
          JD_WEATHER_APP_KEY: ${{ secrets.JD_WEATHER_APP_KEY }}
          WEBHOOK_SERVER_URL: ${{ secrets.WEBHOOK_SERVER_URL }}
          WEIBO_COOKIE: ${{ secrets.WEIBO_COOKIE }}
