name: My Feishu Talk Bot Push
on:
  workflow_dispatch:
    schedules:
      cron: '*/3 * * * *'
jobs:
  run-python-script:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - env:
          JD_WEATHER_APP_KEY: ${{ secrets.JD_WEATHER_APP_KEY }}
          WEBHOOK_SERVER_URL: ${{ secrets.WEBHOOK_SERVER_URL }}
          WEIBO_COOKIE: ${{ secrets.WEIBO_COOKIE }}
          run: |
            pip install -r requirements.txt
            python PushWeiboHotSearchRegularly.py
            python TodayInHistory.py
            python WeatherForecast.py.py
