name: My Feishu Talk Bot Push
jobs:
  run-python-script:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - env:
          JD_WEATHER_APP_KEY: ${{ secrets.JD_WEATHER_APP_KEY }}
          WEBHOOK_SERVER_URL: ${{ secrets.WEBHOOK_SERVER_URL }}
          WEIBO_COOKIE: ${{ secrets.WEIBO_COOKIE }}
        run: |
          pip install requests
          python ./jd_weather.py
      - run: pip install -r requirements.txt
      - run: python PushWeiboHotSearchRegularly.py
      - run: python TodayInHistory.py
      - run: python WeatherForecast.py.py

on:
  workflow_dispatch:
    schedules:
      UTC时间每3分钟执行一次:
        cron: '*/3 * * * *'
